jaffle_shop:
  outputs:

    dev:
      type: bigquery
      method: service-account
      project: vcdispk-event-orch
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      dataset: "{{ env_var('BQ_SCHEMA_PREFIX', 'dev')}}"
      threads: 1
      timeout_seconds: 300
      location: australia-southeast1
      priority: interactive
      retries: 1

  target: dev