
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'jaffle_shop'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

vars:
    'dbt_date:time_zone': 'AUS Eastern Standard Time' # MS format
    default_low_date: '1900-01-01'
    default_low_dttm: '1900-01-01 00:00:00'
    default_high_date: '9999-12-31'
    default_high_dttm: '9999-12-31 23:59:59'
    # adding in below to ease testing
    P_YEAR: 2021
    P_MONTH: 10
    P_DAY: 28

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  jaffle_shop:
    srctx:
      jaffle_shop:
        schema: srctx_jaffle_shop
        tags:
          - srctx.jaffle_shop.srctx_views
    src:
      jaffle_shop:
        schema: src_jaffle_shop
        tags:
          - "src.jaffle_shop"

snapshots:
  jaffle_shop:
    src:    
      jaffle_shop:
        tags:
          - "src.jaffle_shop.snapshots"
